# Generated by Django 4.0.6 on 2022-08-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_userandcommunityinvitation_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAndCommunityInvitation',
        ),
    ]
