# Generated by Django 4.0.6 on 2022-08-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_count_ipandarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000000),
        ),
    ]
